// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export interface MediaItem {
    mediaKey: string;
    dedupKey?: string;
    filename?: string;
    mediaType?: string;
    timestamp?: number;
}

export interface MediaListResult {
    items: MediaItem[];
    nextPageToken?: string;
    stateToken?: string;
}

// Generate a simple hash for method name (for demonstration - in production these would be auto-generated)
function hashCode(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash; // Convert to 32bit integer
    }
    return Math.abs(hash);
}

export function GetMediaList(pageToken: string, limit: number): $CancellablePromise<MediaListResult> {
    return $Call.ByID(hashCode("MediaBrowser.GetMediaList"), pageToken, limit).then(($result: any) => {
        return $result as MediaListResult;
    });
}

export function GetThumbnail(mediaKey: string, size: string): $CancellablePromise<string> {
    return $Call.ByID(hashCode("MediaBrowser.GetThumbnail"), mediaKey, size);
}

export function DownloadMedia(mediaKey: string): $CancellablePromise<string> {
    return $Call.ByID(hashCode("MediaBrowser.DownloadMedia"), mediaKey);
}
